server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webStore
    username: postgres
    password: 9642
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: WebStore
